import React, { useState, useEffect } from "react"
import {BrowserRouter as Router ,Switch, Route} from "react-router-dom"
import {uuid} from "uuidv4";
import './App.css';
import Header from "./Header";
import AddContact from "./AddContact";
import ContactList from "./ContactList"

// install react-router-dom --save package 
//install uuidv4 for unique back end id
//npm i react-router-dom@5.3.0 older package install link. as seen in package json this is 6 version so Switch /// is not working, its replaced by Routes instead//
// uninstall with npm uninstall react-router-dom



function App() {
  const LOCAL_STORAGE_KEY = "contacts"
  const [contacts, setContacts]= useState([{
    id:"1",
    "name":"Berlia",
    "mail":"dk@gmail.com"

}]);

  // const contacts =[
  //   {
  //     id: "1",
  //     name: "John",
  //     email:"john@gmail.com"
  //   },
  //   {
  //     id: "2",
  //     name: "Mary",
  //     email:"mary@gmail.com"
  //   },


  // ]

  // npm i uuidv4


  const addContactHandler=(contact)=>{
  console.log(contact)
  setContacts([...contacts, { id: uuid(), ...contact}]); // adding the unique id generated by uuidv4
};

const removeContactHandler = (id) => { //removing the added contact
  const newContactList= contacts.filter((contact)=>{
    return contact.id !==id;
  });
  setContacts(newContactList)
}

useEffect(() => {
  const retriveContacts = JSON.parse(localStorage.getItem(LOCAL_STORAGE_KEY));
  if (retriveContacts) setContacts(retriveContacts);
}, []);

useEffect(()=>{
  localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(contacts) );

}, [contacts]);

  return (
    <div className="ui container">

      {/* created router and added all three components inside */}
      <Router> 
      <Header />
      <Switch> 
      <Route path="/" exact render ={()=>(<ContactList contacts={contacts} getContactId={removeContactHandler}/>)}/>

      <Route path="/add" render ={()=> (<AddContact addContactHandler={addContactHandler}/>)} />
      

      </Switch>
      
      {/* <AddContact addContactHandler={addContactHandler} />
      <ContactList contacts={contacts} getContactId={removeContactHandler} />  */}




      </Router>
     

    </div>
    
    



  );
}

export default App;
